apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksworkshop
  region: cn-northwest-1
  version: "1.21"

managedNodeGroups:
  - name: ctd
    labels:
      Name: ctd
    instanceType: t3.xlarge
    minSize: 2
    desiredCapacity: 2
    maxSize: 3
    privateNetworking: true
    volumeType: gp3
    volumeSize: 50
    tags:
      nodegroup-name: ctd
    ami: ami-03359a0e76c5425c5
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        certManager: true
        efs: true
        albIngress: true
        xRay: true
        cloudWatch: true
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh eksworkshop --container-runtime containerd