---
apiVersion: v1
kind: Namespace
metadata: 
  name: bigimage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigimage2
  namespace: 	bigimage
  labels:
    app: bigimage2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bigimage2
  template:
    metadata:
      labels:
        app: bigimage2
    spec:
      containers:
      - name: bigimage2
        image: 133129065110.dkr.ecr.ap-southeast-1.amazonaws.com/bigimage:7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bigimage2
  namespace: bigimage
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  selector:
    app: bigimage2
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
